skip_commits:
  files:
    - appveyor.yml
    - README.md

version: 1.0.{build}

configuration: Release

before_build:
  - nuget restore

build:
  verbosity: normal

artifacts:
- path: GeoLocatePSCmdlet\bin\$(configuration)
