skip_commits:
  files:
    - appveyor.yml
    - README.md

version: 1.0.{build}

init:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
      }
      else
      {
        Update-AppveyorBuild -Version "0.0.$($env:APPVEYOR_BUILD_NUMBER)"
      }


configuration: Release

before_build:
  - nuget restore

build:
  verbosity: normal

artifacts:
  - path: GeoLocatePSCmdlet\bin\$(configuration)\*.dll

deploy:
  - provider: GitHub
    draft: true
    description: 'AppVeyor generated build'
    on:
      appveyor_repo_tag: true
    auth_token:
      secure: ANstD90CPeaEG/JTUq4pw8/s0UaGDmIomjvVt3f2tPqnFdD2VhPF8DOlP5AAP2lX
